on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl git python3-vcstool python3-catkin-tools xorg-dev x11-apps
          rosdep update
      - name: Build ROS Package
        id: build
        run: |
          mkdir -p ~/mujoco_ws/src/mujoco
          ln -s $(pwd) ~/mujoco_ws/src/mujoco/mujoco_vendor
          cd ~/mujoco_ws
          rosdep install -yri --from-paths src
          . /opt/ros/noetic/setup.sh
          catkin build
        continue-on-error: true
      - name: Record Build Status
        run: |
          if [ ${{ steps.build.outcome }} == "success" ]; then
          echo "BUILD_STATUS=success" >> $GITHUB_ENV
          else
          echo "BUILD_STATUS=failure" >> $GITHUB_ENV
          fi
      - name: Generate Badges
        run: |
          mkdir -p badges
          curl -o badges/build.svg https://img.shields.io/badge/build-${BUILD_STATUS}-brightgreen
      - name: Deploy Badges to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: badges
      - name: Check Statuses
        run: |
          if [ ${{ steps.build.outcome }} == "failure" ]; then
          exit 1
          fi
