on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ROS environment
        uses: docker://osrf/ros:noetic-desktop-full
      - name: Build ROS Package
        id: build
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          sudo apt install curl # if you haven't already installed curl          
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y python3-vcstool python3-rosdep python3-catkin-tools
          mkdir -p ~/mujoco_ws/src/mujoco
          ln -s $(pwd) ~/mujoco_ws/src/mujoco/mujoco_vendor
          cd ~/mujoco_ws
          rosdep install -yri --from-paths src
          catkin build
        continue-on-error: true
      - name: Record Build Status
        run: |
          if [ ${{ steps.build.outcome }} == "success" ]; then
          echo "BUILD_STATUS=success" >> $GITHUB_ENV
          else
          echo "BUILD_STATUS=failure" >> $GITHUB_ENV
          fi
      - name: Generate Badges
        run: |
          mkdir -p badges
          curl -o badges/build.svg https://img.shields.io/badge/build-${BUILD_STATUS}-brightgreen
      - name: Deploy Badges to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: badges
      - name: Check Statuses
        run: |
          if [ ${{ steps.build.outcome }} == "failure" ]; then
          exit 1
          fi
